### ISSUE TITLE
Conditional File Generation Issue

### ISSUE THREAD

**Issue by SoutaTanaka** [brick-hub/docs.brickhub.dev#17]
**Description**
The current documentation shows that conditional file generation can follow the syntax:
```
├── __brick__
│  └── {{#createChangelog}}CHANGELOG.md{{/createChangelog}}
```
Refs: https://docs.brickhub.dev/brick-syntax#-conditionals

However, using a slash (/) within the file path is required, which cannot be used due to OS-level file name constraints. As a result, conditional file generation does not work as expected. Could you please confirm if this is a bug or provide guidance on an alternative approach?

**Environment**
* Version of the tool being used
  * 0.1.0-dev.55
* Operating System
  * macOS Sonoma 14.3.1

Would appreciate any assistance or clarification on this matter. Thank you!

**Comment by felangel** [comment]
You can physically create subdirectories and/or use `\`. Hope that helps and closing for now!
