### ISSUE TITLE
fix: OS Error: The system cannot find the file specified. , errno = 2 using hello_riverpod

### ISSUE THREAD

**Issue by Raider-hub** [brick-hub/docs.brickhub.dev#6]
When i try to use the command mason add hello_riverpod, i get this error. what exactly is causing this?

E:\test-flutter\new\new_app\mason>mason add hello_riverpod
✓ Installing hello_riverpod (0.7s)
FileSystemException: Cannot open file, path = 'C:/Users/doula/AppData/Local/Mason/Cache/hosted/registry.brickhub.dev/hello_riverpod_0.3.0+8\brick.yaml' (OS Error: The system cannot find the file specified.
, errno = 2)
![Uploading Screenshot (337).png…]()

**Comment by felangel** [comment]
Hi @Raider-hub can you please open mason-related issues in https://github.com/felangel/mason? Thanks!
